### ISSUE TITLE
Website not working

### ISSUE THREAD

**Issue by Maaaaarc** [emmaboecker/railboard#98]
This Project looks really nice from the Screenshots, but sadly, the Page is not working; it shows this Error message:

`Application error: a client-side exception has occurred (see the browser console for more information).`

I tried Firefox and Chrome.

The Browser Logs show the following:
```
app-index.js:31 TypeError: Cannot read properties of undefined (reading 'filter')
    at C (StationSearchBar.tsx:116:24)
    at ri (react-dom.production.min.js:108:254)
    at lp (react-dom.production.min.js:146:170)
    at im (react-dom.production.min.js:265:18)
    at oM (react-dom.production.min.js:249:315)
    at react-dom.production.min.js:247:29
    at oT (react-dom.production.min.js:247:29)
    at ov (react-dom.production.min.js:241:92)
    at nG (react-dom.production.min.js:104:269)
    at nJ (react-dom.production.min.js:105:408)
window.console.error @ app-index.js:31
Show 1 more frame
Show less
```

**Comment by emmaboecker** [comment]
Hi, I pushed a change that introduced a breaking change in the api by accident. the search is fixed now. the db api im using in the background has some hiccups rn tho, so it might still not work to view station boards. I did find something new today tho which means there is going to be a change of db apis soon (which will probably make it a lot more reliable. thanks for noticing!)
